insert into department_types (department_type) values ('organisation');
insert into department_types (department_type) values ('department');
insert into department_types (department_type) values ('division');
insert into department_types (department_type) values ('section');

insert into employee_positions (employee_position) values ('director');
insert into employee_positions (employee_position) values ('designer');
insert into employee_positions (employee_position) values ('analyst');
insert into employee_positions (employee_position) values ('manager');
insert into employee_positions (employee_position) values ('developer');

insert into departments (department_name, department_type) values ('organisation', 1);
insert into departments (department_name, department_type, parent_department) values ('department1', 2, 1);
insert into departments (department_name, department_type, parent_department) values ('department2', 2, 1);
insert into departments (department_name, department_type, parent_department) values ('division1', 3, 2);
insert into departments (department_name, department_type, parent_department) values ('division2', 3, 2);
insert into departments (department_name, department_type, parent_department) values ('division3', 3, 3);
insert into departments (department_name, department_type, parent_department) values ('division4', 3, 3);
insert into departments (department_name, department_type, parent_department) values ('section1', 4, 4);
insert into departments (department_name, department_type, parent_department) values ('section2', 4, 4);
insert into departments (department_name, department_type, parent_department) values ('section3', 4, 5);
insert into departments (department_name, department_type, parent_department) values ('section4', 4, 5);
insert into departments (department_name, department_type, parent_department) values ('section5', 4, 6);
insert into departments (department_name, department_type, parent_department) values ('section6', 4, 6);
insert into departments (department_name, department_type, parent_department) values ('section7', 4, 7);
insert into departments (department_name, department_type, parent_department) values ('section8', 4, 7);

insert into users (password, role, username) VALUES ('$2a$10$MsmL9LkIvVlxXIPOZhJJiu.3g4b/EdKmxdWt6DTT47mkTn56EE/6.', 'ROLE_ADMINISTRATOR', 'amdin');




insert into employees (employee_info, department_id, position_id) values ('Katlin Brunnstein', 11, 2);
insert into employees (employee_info, department_id, position_id) values ('Alexis Pidduck', 9, 1);
insert into employees (employee_info, department_id, position_id) values ('Ilse Yanyshev', 9, 3);
insert into employees (employee_info, department_id, position_id) values ('Christian Grishanin', 1, 2);
insert into employees (employee_info, department_id, position_id) values ('Chan Botham', 2, 5);
insert into employees (employee_info, department_id, position_id) values ('Jeramey MacCaghan', 15, 2);
insert into employees (employee_info, department_id, position_id) values ('Jermaine McGarel', 3, 2);
insert into employees (employee_info, department_id, position_id) values ('Bryn Boller', 15, 1);
insert into employees (employee_info, department_id, position_id) values ('Meta Ballingal', 13, 5);
insert into employees (employee_info, department_id, position_id) values ('Pavlov Chilley', 6, 1);
insert into employees (employee_info, department_id, position_id) values ('Cthrine Rulf', 7, 5);
insert into employees (employee_info, department_id, position_id) values ('Ahmed Davids', 1, 5);
insert into employees (employee_info, department_id, position_id) values ('Derron Georgel', 6, 5);
insert into employees (employee_info, department_id, position_id) values ('Ernest Benedite', 14, 1);
insert into employees (employee_info, department_id, position_id) values ('Desmund Tice', 15, 5);
insert into employees (employee_info, department_id, position_id) values ('Rhonda Emms', 10, 2);
insert into employees (employee_info, department_id, position_id) values ('Aleda Mulliner', 8, 2);
insert into employees (employee_info, department_id, position_id) values ('Madalyn Gwilym', 13, 5);
insert into employees (employee_info, department_id, position_id) values ('Everett Aizik', 2, 5);
insert into employees (employee_info, department_id, position_id) values ('Dorette Sayers', 14, 5);
insert into employees (employee_info, department_id, position_id) values ('Merle McKelloch', 7, 5);
insert into employees (employee_info, department_id, position_id) values ('Alicia Vedntyev', 11, 3);
insert into employees (employee_info, department_id, position_id) values ('Hamlin Tellesson', 5, 4);
insert into employees (employee_info, department_id, position_id) values ('Joannes Bwy', 11, 5);
insert into employees (employee_info, department_id, position_id) values ('Amory Nordass', 3, 5);
insert into employees (employee_info, department_id, position_id) values ('Chlo Raddan', 11, 4);
insert into employees (employee_info, department_id, position_id) values ('Beatrix MacNish', 14, 3);
insert into employees (employee_info, department_id, position_id) values ('Erastus Chadband', 6, 4);
insert into employees (employee_info, department_id, position_id) values ('Constance Eberst', 13, 5);
insert into employees (employee_info, department_id, position_id) values ('Franni Tims', 15, 4);
insert into employees (employee_info, department_id, position_id) values ('Bettine Gibard', 14, 2);
insert into employees (employee_info, department_id, position_id) values ('Trev Stark', 10, 4);
insert into employees (employee_info, department_id, position_id) values ('Rowland Barson', 12, 3);
insert into employees (employee_info, department_id, position_id) values ('Garry MacLise', 11, 1);
insert into employees (employee_info, department_id, position_id) values ('Gates Hydes', 3, 3);
insert into employees (employee_info, department_id, position_id) values ('Noll MacGragh', 8, 4);
insert into employees (employee_info, department_id, position_id) values ('Thibaut Pettiford', 7, 2);
insert into employees (employee_info, department_id, position_id) values ('Trixy Matanin', 3, 1);
insert into employees (employee_info, department_id, position_id) values ('Cherri Adrian', 2, 3);
insert into employees (employee_info, department_id, position_id) values ('Mercy Warnock', 9, 2);
insert into employees (employee_info, department_id, position_id) values ('Robina Swinnard', 6, 2);
insert into employees (employee_info, department_id, position_id) values ('Yurik Griswood', 15, 5);
insert into employees (employee_info, department_id, position_id) values ('Helene McQuirter', 1, 1);
insert into employees (employee_info, department_id, position_id) values ('Brandon Mulroy', 1, 2);
insert into employees (employee_info, department_id, position_id) values ('Jessamine Poll', 3, 4);
insert into employees (employee_info, department_id, position_id) values ('Dorthy Simononsky', 12, 1);
insert into employees (employee_info, department_id, position_id) values ('Danielle Pleming', 10, 2);
insert into employees (employee_info, department_id, position_id) values ('Aigneis Spriggs', 11, 5);
insert into employees (employee_info, department_id, position_id) values ('Cullin Pleven', 1, 3);
insert into employees (employee_info, department_id, position_id) values ('Amalita Dodle', 4, 2);
insert into employees (employee_info, department_id, position_id) values ('Enos Cowpertwait', 3, 3);
insert into employees (employee_info, department_id, position_id) values ('Berta Batchelour', 8, 1);
insert into employees (employee_info, department_id, position_id) values ('Patrice Juster', 5, 1);
insert into employees (employee_info, department_id, position_id) values ('Maynard Bolton', 14, 2);
insert into employees (employee_info, department_id, position_id) values ('Ewan Bielefeld', 7, 1);
insert into employees (employee_info, department_id, position_id) values ('Leo Gori', 4, 3);
insert into employees (employee_info, department_id, position_id) values ('Elwyn Fluger', 5, 2);
insert into employees (employee_info, department_id, position_id) values ('Hildegarde Mirams', 8, 4);
insert into employees (employee_info, department_id, position_id) values ('Gregory Ready', 7, 3);
insert into employees (employee_info, department_id, position_id) values ('Jeromy Tivenan', 13, 1);
insert into employees (employee_info, department_id, position_id) values ('Angelique Duchenne', 9, 2);
insert into employees (employee_info, department_id, position_id) values ('Arthur Munnis', 14, 5);
insert into employees (employee_info, department_id, position_id) values ('Opaline Wooster', 3, 3);
insert into employees (employee_info, department_id, position_id) values ('Chas McNulty', 14, 4);
insert into employees (employee_info, department_id, position_id) values ('Woodie Jackling', 12, 3);
insert into employees (employee_info, department_id, position_id) values ('Cybill Burras', 11, 2);
insert into employees (employee_info, department_id, position_id) values ('Barron Doxey', 2, 5);
insert into employees (employee_info, department_id, position_id) values ('Dusty Bubb', 2, 1);
insert into employees (employee_info, department_id, position_id) values ('Heinrick Panas', 10, 1);
insert into employees (employee_info, department_id, position_id) values ('Lindsay Bladesmith', 4, 1);
insert into employees (employee_info, department_id, position_id) values ('Addie Wylam', 10, 3);
insert into employees (employee_info, department_id, position_id) values ('Bunnie Hempshall', 1, 2);
insert into employees (employee_info, department_id, position_id) values ('Decca Cicutto', 3, 5);
insert into employees (employee_info, department_id, position_id) values ('Angelita Leeke', 13, 3);
insert into employees (employee_info, department_id, position_id) values ('Jabez Stanyan', 14, 3);
